// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_P-5OYIyPILaHKixegJOd7WzSlYAqvGs',
    appId: '1:590251982137:web:e995e4149fc11e1fd2bce8',
    messagingSenderId: '590251982137',
    projectId: 'doanmobile-48887',
    authDomain: 'doanmobile-48887.firebaseapp.com',
    databaseURL: 'https://doanmobile-48887-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'doanmobile-48887.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgWyY6j6aNCztaStvxWKGMimvBIK4EhVo',
    appId: '1:590251982137:android:9c371906f996f670d2bce8',
    messagingSenderId: '590251982137',
    projectId: 'doanmobile-48887',
    databaseURL: 'https://doanmobile-48887-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'doanmobile-48887.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgK1O4XrdW2JqwUS2H0TY68z2S6vLoBbU',
    appId: '1:590251982137:ios:df3e8a8b8303bbd1d2bce8',
    messagingSenderId: '590251982137',
    projectId: 'doanmobile-48887',
    databaseURL: 'https://doanmobile-48887-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'doanmobile-48887.firebasestorage.app',
    iosBundleId: 'com.example.expanseManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgK1O4XrdW2JqwUS2H0TY68z2S6vLoBbU',
    appId: '1:590251982137:ios:df3e8a8b8303bbd1d2bce8',
    messagingSenderId: '590251982137',
    projectId: 'doanmobile-48887',
    databaseURL: 'https://doanmobile-48887-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'doanmobile-48887.firebasestorage.app',
    iosBundleId: 'com.example.expanseManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_P-5OYIyPILaHKixegJOd7WzSlYAqvGs',
    appId: '1:590251982137:web:5f80fd0f0d8f02d3d2bce8',
    messagingSenderId: '590251982137',
    projectId: 'doanmobile-48887',
    authDomain: 'doanmobile-48887.firebaseapp.com',
    databaseURL: 'https://doanmobile-48887-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'doanmobile-48887.firebasestorage.app',
  );
}
